name: save_pesa
description: A Flutter project scaffolded in-place.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  sqflite: ^2.3.0
  path: ^1.8.3
  http: ^1.1.0
  intl: ^0.18.1
  permission_handler: ^11.0.1
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  telephony: ^0.2.0
  flutter_contacts: ^1.1.9+2
  image_picker: ^1.0.7
  google_mlkit_text_recognition: ^0.11.0
  local_auth: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
